name = "tide-api-proxy"
main = "src/index.js"
compatibility_date = "2025-05-06"

[[kv_namespaces]]
binding = "VISITOR_STORE"
id = "cd2306ce540a4402907f4610b1e19368"

[observability]
enabled = false

[triggers]
crons = ["0 17 * * *"]   # 17:00 UTC = 02:00 KST (매일 새벽 2시 사전 캐싱)
